### PR TITLE
Add ALB name and Target Group Name as outputs

### PR DESCRIPTION
**Pull request by nicolaei**

### CODE REVIEW

**Comment by stekern** [comment]
Is this for CloudWatch metrics for the ALB? If so I believe you need the `arn_suffix` attribute of the ALB and target group, not the `name`

**Comment by nicolaei** [comment]
You're right! Fixed.

**Comment by stekern** [comment]
I think you still need an output for the `arn_suffix` attribute of the target group, no? This is at least required for CloudWatch metrics such as `HealthyHostCount` in the `AWS/ApplicationELB` namespace 👀

**Comment by nicolaei** [comment]
That is right, thanks for catching it! Fixed now.

**Review by stekern — APPROVED** [review]
LGTM 👍

**Pull request merged**
